# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2af88c3e657ed51ae1c9c440ff0383cc6e642632d118829f20d451b57739a665cacecbf12388bd7f21b7cfd5415c1a343dbb8745f5176a9a23dc38f92182d58a

test:
  secret_key_base: e13264aaea2210dd38f0f313428f3e1a34b6cd0d6dfa7ece75cad94e4801dfe5036f5f4629091547c6604106db58d4c1c82599570883085dc990a7ed14c2c697

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
